
output "key_id" {
  description = "A UUID used to uniquely identify this password credential"
  value       = azuread_service_principal_password.pwd.key_id
}
output "value" {
  description = "The password for this service principal, which is generated by Azure Active Directory"
  value       = azuread_service_principal_password.pwd.value
  sensitive   = true
}
output "service_principal_id" {
  description = "The service principal ID"
  value       = azuread_service_principal_password.pwd.service_principal_id
}
output "end_date" {
  description = "The end date until which the password is valid, formatted as an RFC3339 date string (e.g. 2018-01-01T01:02:03Z)"
  value       = azuread_service_principal_password.pwd.end_date
}
output "end_date_relative" {
  description = "A relative duration for which the password is valid until, for example 240h (10 days) or 2400h30m"
  value       = azuread_service_principal_password.pwd.end_date_relative
}
output "start_date" {
  description = "The start date from which the password is valid, formatted as an RFC3339 date string (e.g. 2018-01-01T01:02:03Z)"
  value       = azuread_service_principal_password.pwd.start_date
}
output "keyvaults" {
  description = "Keyvaults storing the passwords. Store the secret_prefix-client-id, secret_prefix-client-secret"
  value = {
    for key, value in try(var.settings.keyvaults, {}) : key => {
      id                        = try(azurerm_key_vault_secret.client_id[key].key_vault_id, null)
      secret_name_client_secret = try(value.secret_prefix, "SP")
    }
  }
}
